### PR TITLE
Randomizing anon users

### PR DESCRIPTION
**Pull request by smubarak7**
Added a feature to randomize username and profile pictures, for anonymous users, similar to google docs.

### CODE REVIEW

**Comment by jdaouddd** [comment]
Good code, functioning well except that coverage went down for Postgres and that needs investigation.

**Review by jdaouddd — COMMENTED** [review]
Good code, and functional. Coverage went down for Postgres that needs investigating.

**Review by boushrabnd — APPROVED** [review]
The mongo dev coveralls are not working for some reason but looks good

**Comment by boushrabnd** [comment]
Merging this pull request because the coveralls went down after we added something to the userGuide

**Pull request merged**
